name: Run tests and upload coverage
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"
      - name: Install dependencies
        run: pip install --group ci
      - name: Run tests
        run: pytest
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          fail_ci_if_error: true
          directory: ./coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
